defmodule Clouds.Users.User do
  import Ecto.Changeset
  use Ecto.Schema
  use Pow.Ecto.Schema

  use Pow.Extension.Ecto.Schema,
    extensions: [PowPersistentSession]

  alias CloudsWeb.Router.Helpers, as: Routes

  schema "users" do
    field :name, :string
    field :summary, :string
    field :username, :string

    # Autogenerated fields
    field :pub_key, :string
    field :priv_key, :string

    pow_user_fields()

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> pow_changeset(attrs)
    |> pow_extension_changeset(attrs)
    |> cast(attrs, [:name, :username, :summary])
    |> maybe_generate_pub_key_pair
    |> validate_required([:name, :username, :pub_key, :priv_key, :summary])
    |> unique_constraint(:username)
  end

  @doc false
  defp maybe_generate_pub_key_pair(changeset) do
    case get_field(changeset, :priv_key) do
      nil ->
        {:ok, {priv, pub}} = RsaEx.generate_keypair()

        changeset
        |> put_change(:priv_key, priv)
        |> put_change(:pub_key, pub)

      _ ->
        changeset
    end
  end

  def to_actor(%Clouds.Users.User{} = user) do
    %{
      "@context" => [
        "https://www.w3.org/ns/activitystreams",
        "https://w3id.org/security/v1"
      ],
      "id" => "#{Clouds.url()}",
      "type" => "Person",
      "preferredUsername" => user.username,
      "inbox" => inbox_url(user),
      "publicKey" => %{
        "id" => pubkey_url(user),
        "owner" => actor_url(user),
        "publicKeyPem" => user.pub_key
      }
    }
  end

  def actor_url(%Clouds.Users.User{} = user) do
    Routes.user_url(CloudsWeb.Endpoint, :show, user)
  end

  def inbox_url(%Clouds.Users.User{} = user) do
    Routes.user_url(CloudsWeb.Endpoint, :inbox, user)
  end

  def pubkey_url(%Clouds.Users.User{} = user) do
    actor_url(user) <> "#main-key"
  end
end
